### ISSUE TITLE
Tiny::from return 0 if an integer obfuscated id is used

### ISSUE THREAD

**Issue by ingro** [zackkitzmiller/tiny-php#13]
Hello! I've found this edge case by returning the ids generated from Tiny to the client in json format, which encode numbers as integer. If later i pass back this value to the server to get the original id it returns 0. Maybe it could be resolved just by typecasting the value feeded inside the `from` method? Or is this an intended behaviour?

```php
<?php

require('vendor/autoload.php');

$tiny = new \ZackKitzmiller\Tiny('randomkey');

echo $tiny->to(869);
// 87

echo '<br>';

// Later...

echo $tiny->from(87);
// 0

echo $tiny->from('87');
// 869
```

**Comment by zackkitzmiller** [comment]
`from` is definitely expecting a string. You shouldn't need to typecase because the parameter to `from` will often look like `8xK`.
