### ISSUE TITLE
maybe tag at least 1.1.1?

### ISSUE THREAD

**Issue by huglester** [zackkitzmiller/tiny-php#15]
Hello,

I think many improvements have been added. Would be good to gave it tagged! 

EDIT:

I was checking here: https://github.com/zackkitzmiller/tiny-php/releases
But composer installs 1.2.1 already. Not sure how to track it down! :)

Please close if not needed.

Thanks
Jaroslav

**Comment by zackkitzmiller** [comment]
I'll check this out today.

**Comment by zackkitzmiller** [comment]
1.2.1 is the most recent version.
