### ISSUE TITLE
Consider a name change.

### ISSUE THREAD

**Issue by frankdejonge** [zackkitzmiller/tiny-php#17]
To me, the name Tiny only resonates with how much code is in the repository, besides that, I haven't got a single clue to why it's named that way. Perhaps a name change can help to clarify what the package is for? I saw the branch to prepare it for a league proposal, guessed it would be the right time to propose this.

Disclaimer: I might not have understood the name if it was something clever.

**Comment by zackkitzmiller** [comment]
This package takes a long primary key (e. g. 1827478492991936) and makes it Tiny (7bF1). 

At this point I think for too many people are using Tiny in various languages to change the name.

**Comment by frankdejonge** [comment]
@zackkitzmiller gotcha, I didn't know this name was used in a broader scope.
