### ISSUE TITLE
Composer instructions obsolete

### ISSUE THREAD

**Issue by jeteon** [zackkitzmiller/tiny-php#18]
The README suggests that you can install this package via:

`composer require league/tiny`

There is no longer such a package on Packagist, however. I managed to install it using:

`composer require zackkitzmiller/tiny`

but believe this is also somewhat dated. It does work though. I think updating it to the current one would really help others get hold of and use this great and petite package.

**Comment by aranw** [comment]
I came into this issue when trying to install Tiny. 

Also the zakkitzmiller version has a different namespace

**Comment by zackkitzmiller** [comment]
I've actually reverted the commit that was preparing this library for the PHP League. It had some bugs in it. The Readme should be good to know now.
