### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mr-lanholmes** [zackkitzmiller/tiny-php#21]
I use this key
tLx55bnGfSZ2qPYZ8DvUEQBsgS3NGY2UZ6rCyvrSWYsBU6FrLJtCeufWZgppfs4jHDdtnNdjeS7pLCnPq9PnDeM762pTmPchJsJScKQgDJDRx6FLZkRVGcwV

And 

try to obfuscate my ID 3 and 4, both onfuscated to 5.

Edit:
I also use this key
DHYsTLYpxuWZtUnZFpPGy9dUXZeqerD3K2sqZkYkwmUX8KPG8R7u3BL4ewF4Uf

And I try to return back the obfuscated result 
My real ID: 15 after obfuscated and try to return it back it give me 11

Thanks

**Comment by zackkitzmiller** [comment]
From the docs: 

> You must instanciate a new instance of Tiny with a random alpha-numeric set where each character must only be used exactly once.

Both of your keys had duplicated characters. I'd be happy to investigate a solution that uses repeats, but that would be a larger under taking

**Comment by mr-lanholmes** [comment]
Hi @zackkitzmiller .  Sorry my mistakes. Thanks for the help, Appreciate it very much.
