### ISSUE TITLE
Bump release version

### ISSUE THREAD

**Issue by dangreaves** [zackkitzmiller/tiny-php#28]
Hey guys,

Would it be possible to create a release to include L5 support made in ab1ac2e.

At the moment, `dev-master` has to be used to include it.

**Comment by eliottrobson** [comment]
Still need this in 2017 :)

**Comment by jjok** [comment]
Still need this in 2008 :)

**Comment by zackkitzmiller** [comment]
Did I not do this? I’ll do it today.

**Comment by josegonzalez** [comment]
I don't need this in 2020.

**Comment by josegonzalez** [comment]
I need this in 2021 @zackkitzmiller

**Comment by dangreaves** [comment]
Closing this. After 8 years, I think @zackkitzmiller may have moved on to something new 🤣

**Comment by zackkitzmiller** [comment]
Did I?

**Comment by josegonzalez** [comment]
Zack give us a release.
