### ISSUE TITLE
Incompatible with Laravel 5.4 due to use of `share` method in service provider

### ISSUE THREAD

**Issue by dangreaves** [zackkitzmiller/tiny-php#30]
Use of the `share` method for registering singletons has been deprecated in Laravel 5.4 in favour of the `singleton` method.

Please see PR at https://github.com/zackkitzmiller/tiny-php/pull/29 which replaces use of the share method in the Laravel 5 service provider.

**Comment by josemf** [comment]
I guys, 

I don't think the version 1.3.0 fixed this issue (on #29 comments).

Thanks!

vagrant@rio:~/rio/backend$ composer show zackkitzmiller/tiny
name     : zackkitzmiller/tiny
descrip. : A reversible base62 ID obfuscater.
keywords : 
versions : * 1.3.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/zackkitzmiller/tiny-php.git e023cc1ba14dafcb10372e8d9fb4ebdc43f1be71
dist     : [zip] https://api.github.com/repos/zackkitzmiller/tiny-php/zipball/e023cc1ba14dafcb10372e8d9fb4ebdc43f1be71 e023cc1ba14dafcb10372e8d9fb4ebdc43f1be71
names    : zackkitzmiller/tiny
 
vagrant@rio:~/rio/backend$ php artisan config:publish zackkitzmiller/tiny
PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::share() in /home/vagrant/rio/backend/vendor/zackkitzmiller/tiny/src/ZackKitzmiller/TinyServiceProvider.php on line 21
PHP Stack trace:
PHP   1. {main}() /home/vagrant/rio/backend/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/rio/backend/artisan:36
PHP   3. Illuminate\Foundation\Console\Kernel->bootstrap() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:115
PHP   4. Illuminate\Foundation\Application->bootstrapWith() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:270
PHP   5. Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:208
PHP   6. Illuminate\Foundation\Application->registerConfiguredProviders() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php:17
PHP   7. Illuminate\Foundation\ProviderRepository->load() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:543
PHP   8. Illuminate\Foundation\Application->register() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:74
PHP   9. ZackKitzmiller\TinyServiceProvider->register() /home/vagrant/rio/backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:568

                                                                       
  [Symfony\Component\Debug\Exception\FatalErrorException]              
  Call to undefined method Illuminate\Foundation\Application::share()

**Comment by dangreaves** [comment]
Ensure you are registering `ZackKitzmiller\Laravel5\TinyServiceProvider`.

`ZackKitzmiller\TinyServiceProvider` is for Laravel 4.

**Comment by josemf** [comment]
Thank you Dan,

Works now.
